name: CI

on:
  push:
    branches:
      - master
      - '*.x'
    tags:
      - '*'
  pull_request:
  schedule:
    # Weekly Monday 7AM build
    - cron: "0 7 * * 1"

jobs:
  ci:
    name: Python ${{ matrix.python-version }}, numpy${{ matrix.numpy-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.7
            numpy-version: "~=1.14.0"
        python-version: [3.7, 3.8, 3.9]
        numpy-version: ["~=1.17.0", "~=1.19.0", ""]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install stsci.image
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test] numpy${{ matrix.numpy-version }}

      - name: Run tests
        run: |
          pytest
